name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      DEFCONFIG:
        description: Defconfig
        default: 'rsuntk_defconfig'
        required: true
      BRANCH:
        description: Branch
        default: ''
        required: true
      GOOGLE:
        description: Use Google toolchains instead of proton-clang
        type: boolean
      KSU:
        description: Add KernelSU support
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: rsuntkOrgs/android_kernel_samsung_a05
        ref: ${{ github.event.inputs.BRANCH }}
        path: android_kernel_samsung_a05
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Fetch toolchains
      run: |
        mkdir toolchains
        cd toolchains
        if [[ ${{ github.event.inputs.GOOGLE }} == "true" ]]; then
          git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/clang-toolchains.git clang-11
          git clone --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-6.4.1.git gnu
        else
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git
        fi
      working-directory: android_kernel_samsung_a05

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      
    - name: Build kernel
      id: buildKernel
      run: |
        if [[ "${{ github.event.inputs.GOOGLE }}" = "true" ]]; then
          export PATH=$(pwd)/toolchains/clang-11/bin:$PATH
          export CROSS_COMPILE=$(pwd)/toolchains/gnu/bin/aarch64-linux-gnu-
        else
          export PATH=$(pwd)/toolchains/proton-clang/bin:$PATH
          export CROSS_COMPILE=$(pwd)/toolchains/proton-clang/bin/aarch64-linux-gnu-
        fi
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"

        export KBUILD_BUILD_USER="rsuntk"
        export KBUILD_BUILD_HOST="rsuntk_orgs"
        export DEVICE=A055X

        # do some checks
        echo ""
        echo ====================================================
        echo CROSS_COMPILE=$CROSS_COMPILE
        echo DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"
        echo CLANG="`clang -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`"
        echo CLANG_TRIPLE=$CLANG_TRIPLE
        echo KBUILD_BUILD_USER=$KBUILD_BUILD_USER
        echo KBUILD_BUILD_HOST=$KBUILD_BUILD_HOST
        echo CURRENT_DIR=$(pwd)
        echo DATE=`date`
        echo KERNELSU="${{ github.event.inputs.KSU }}"
        echo UPLOAD_2_TG="${{ github.event.inputs.UPLOAD_TG }}"
        echo ====================================================
        echo ""
        
        if [[ ${{ github.event.inputs.KSU }} = "true" ]]; then
        	curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
        fi
        
        bash $(pwd)/build_kernel.sh
        echo ""
        echo "===================================================="
        strings out/arch/arm64/boot/Image | grep "Linux version"
        echo "===================================================="
        mv out/.config out/build_config.txt
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="`make kernelversion`-`echo $DEVICE`_`echo $gitsha1`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
      working-directory: android_kernel_samsung_a05
      
    - name: Upload config
      uses: actions/upload-artifact@v4
      with:
        name: Config-${{ steps.buildKernel.outputs.buildDetails }}
        path: android_kernel_samsung_a05/out/build_config.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          android_kernel_samsung_a05/out/arch/arm64/boot/*.gz
          android_kernel_samsung_a05/out/arch/arm64/boot/dts/mediatek/*.dtb

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          android_kernel_samsung_a05/AnyKernel3/*
