name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      DEFCONFIG:
        description: Defconfig
        default: 'rsuntk_defconfig'
        required: true
      LLVM:
        description: LLVM compiling
        type: boolean
      GOOGLE:
        description: Use Google toolchains instead of proton-clang
        type: boolean
      UPLOAD_TG:
        description: Upload it to telegram
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: rsuntkOrgs/android_kernel_samsung_a12s
        ref: android-4.19-stable
        path: android_kernel_samsung_a12s
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Fetch toolchains
      run: |
        mkdir toolchains
        cd toolchains
        if [[ ${{ github.event.inputs.GOOGLE }} == "true" ]]; then
          git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/clang-toolchains.git clang-11
          git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/aarch64-linux-android.git google
        else
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git
        fi
      working-directory: android_kernel_samsung_a12s

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      
    - name: Build kernel
      run: |
        if [[ ${{ github.event.inputs.GOOGLE }} == "true" ]]; then
          export PATH=$(pwd)/toolchains/clang-11/bin:$PATH
          export CROSS_COMPILE=$(pwd)/toolchains/google/bin/aarch64-linux-android-
        else
          export PATH=$(pwd)/toolchains/proton-clang/bin:$PATH
          export CROSS_COMPILE=$(pwd)/toolchains/proton-clang/bin/aarch64-linux-gnu-
        endif
        export CLANG_TRIPLE=aarch64-linux-gnu-
        export DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"
        export LLVM_STATE="${{ github.event.inputs.LLVM }}"

        export KBUILD_BUILD_USER="rsuntk"
        export KBUILD_BUILD_HOST="rsuntk_orgs"

        # do some checks
        echo ""
        echo ====================================================
        echo CROSS_COMPILE=$CROSS_COMPILE
        echo DEFCONFIG="${{ github.event.inputs.DEFCONFIG }}"
        echo CLANG=`clang -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`
        echo CLANG_TRIPLE=$CLANG_TRIPLE
        echo KBUILD_BUILD_USER=$KBUILD_BUILD_USER
        echo KBUILD_BUILD_HOST=$KBUILD_BUILD_HOST
        echo CURRENT_DIR=$(pwd)
        echo DATE=`date`
        echo ====================================================
        echo ""
        
        curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
        bash $(pwd)/build_kernel.sh
        echo ""
        echo "===================================================="
        strings out/arch/arm64/boot/Image | grep "Linux version"
        echo "===================================================="
        mv out/.config config.txt && cp out/arch/arm64/boot/Image $GITHUB_WORKSPACE/AnyKernel3/Image
      working-directory: android_kernel_samsung_a12s
      
    - name: Upload config
      uses: actions/upload-artifact@v4
      with:
        name: CONFIG
        path: android_kernel_samsung_a12s/out/config.txt
        
    - name: Upload to telegram
      if: github.events.input.UPLOAD_TG == true
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Kernel
      run: |
        if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          zipName="A127F_UC-${{ github.sha }}.zip"
          cd $GITHUB_WORKSPACE/AnyKernel3 && zip -r9 ../$zipName *
          bash $GITHUB_WORKSPACE/.github/scripts/upload_handler.sh $GITHUB_WORKSPACE/$zipName
        else
          echo "Telegram bot token is undefined, please add it to repository secrets!"
          exit 1
        fi
        
    - name: Upload .gz
      uses: actions/upload-artifact@v4
      with:
        name: Image-gz
        path: android_kernel_samsung_a12s/out/arch/arm64/boot/*.gz
