name: Build Kernel
on:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: TG
    steps:
    - uses: actions/checkout@v4
      with:
        repository: rsuntkOrgs/android_kernel_samsung_a12s
        path: android_kernel_samsung_a12s
        show-progress: false
        fetch-depth: 1
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Fetch toolchains
      run: |
        mkdir toolchains
        cd toolchains
        #git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/clang-toolchains.git clang-11
        #git clone --depth=1 https://gitlab.com/Rissu-Projekt/toolchains/aarch64-linux-android.git google
        git clone --depth=1 https://github.com/kdrag0n/proton-clang.git
      working-directory: android_kernel_samsung_a12s

    - name: Prepare timezone fix
      run: |
        sudo rm /etc/localtime
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      
    - name: Build kernel
      id: buildKernel
      run: |
        #export PATH=$(pwd)/toolchains/clang-11/bin:$PATH
        #export CROSS_COMPILE=$(pwd)/toolchains/google/bin/aarch64-linux-android-
        export PATH=$(pwd)/toolchains/proton-clang/bin:$PATH
        export CROSS_COMPILE=$(pwd)/toolchains/proton-clang/bin/aarch64-linux-gnu-
        export CLANG_TRIPLE=aarch64-linux-gnu-

        export KBUILD_BUILD_USER="rsuntk"
        export KBUILD_BUILD_HOST="rsuntk_orgs"

        # do some checks
        echo ""
        echo ====================================
        echo CROSS_COMPILE=$CROSS_COMPILE
        echo CLANG=`clang -v`
        echo CLANG_TRIPLE=$CLANG_TRIPLE
        echo KBUILD_BUILD_USER=$KBUILD_BUILD_USER
        echo KBUILD_BUILD_HOST=$KBUILD_BUILD_HOST
        echo CURRENT_DIR=$(pwd)
        echo DATE=`date`
        echo ====================================
        echo ""
        
        curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
        bash $(pwd)/build_kernel.sh
      working-directory: android_kernel_samsung_a12s
      
    - name: Upload .gz
      uses: actions/upload-artifact@v4
      with:
        name: Image-gz
        path: android_kernel_samsung_a12s/out/arch/arm64/boot/*.gz
