name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Kernel branch
        default: 'linux-4.19.y'
        required: true
      DEFCONFIG: 
        description: Defconfig (only for a05m)
        default: 'rsuntk-a05m_defconfig'
        required: false
      TARGET_DEVICE:
        description: Target device
        required: true
        default: 'a05m'
        type: choice
        options:
          - a05m
          - a04
      LTO:
        description: 'Link Time Optimisation'
        required: true
        default: 'none'
        type: choice
        options:
          - none
          - thin
          - full
      KSU:
        description: Add KernelSU support
        type: boolean
      UPLOAD_TO_TG:
        description: Upload to Telegram
        type: boolean
      UPLOAD_LKM:
        description: Upload LKM
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: telegramUpload
    steps:
    - name: Get date
      id: rundate
      run: sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "REPO_DATE=`date`" >> $GITHUB_OUTPUT
    
    - name: Get device target
      id: getdev
      run: |
        DEVICE_TARGET="${{ github.event.inputs.TARGET_DEVICE }}"
        if [[ "$DEVICE_TARGET" = "a05m" ]]; then
          CHAT_IDX="${{ secrets.CHAT_ID_A05 }}"
          DEFCONFIGX="${{ github.event.inputs.DEFCONFIG }}"
          DEVICE_MODEL="A055F"
          DEVICE="a05m"
          DEVICE_ID="A05"
        elif [[ "$DEVICE_TARGET" = "a04" ]]; then
          CHAT_IDX="${{ secrets.CHAT_ID }}"
          DEFCONFIGX="rsuntk-a04_defconfig"
          DEVICE_MODEL="A045F"
          DEVICE="a04"
          DEVICE_ID="A04"
        fi

        echo "DEVICE=$DEVICE" >> $GITHUB_OUTPUT
        echo "DEVICE_MODEL=$DEVICE_MODEL" >> $GITHUB_OUTPUT
        echo "DEFCONFIG=$DEFCONFIGX" >> $GITHUB_OUTPUT
        echo "CHAT_ID=$CHAT_IDX" >> $GITHUB_OUTPUT
        echo "DEVICE_ID=$DEVICE_ID" >> $GITHUB_OUTPUT
    
    - uses: actions/checkout@v4
      with:
        path: kernel_root
        repository: "rsuntkOrgs/kernel_samsung_wingtech"
        ref: ${{ github.event.inputs.BRANCH }}
        show-progress: false
        fetch-depth: 1
        
    - name: Telegram msg
      if: github.event.inputs.UPLOAD_TO_TG == 'true'
      uses: cbrgm/telegram-github-action@v1
      with:
        to: ${{ steps.getdev.outputs.CHAT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        disable-web-page-preview: true
        parse-mode: html
        message: |
          @${{ github.actor }} triggered a kernel build!
          <b>Start:</b> ${{ steps.rundate.outputs.REPO_DATE }}
          <b>Device:</b> ${{ steps.getdev.outputs.DEVICE }}
          <b>Branch:</b> ${{ github.event.inputs.BRANCH }}
          <b>Workflows:</b> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          <b>Repository:</b> https://github.com/rsuntkOrgs/kernel_samsung_wingtech
        
    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
        sudo aptitude install libssl-dev -y
        
    - name: Fetch toolchains
      run: |
        mkdir toolchains
        cd toolchains
        echo "[+] Cloning Android clang 16"
        #URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz"
        URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-release/clang-r475365b.tar.gz"
        
        mkdir clang && cd clang
        wget -q -O clang.tar.gz $URL 
        tar -xf clang.tar.gz && rm clang.tar.gz && cd ..
        #git clone --single-branch --depth=1 https://github.com/rsuntk/toolchains.git -b clang-11 clang
        git clone --single-branch --depth=1 https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-gnu-6.4.1.git gnu
      working-directory: kernel_root
      
    - name: Build kernel
      id: buildKernel
      run: |
        export PATH=$(pwd)/toolchains/clang/bin:$PATH
        export CROSS_COMPILE="$(pwd)/toolchains/gnu/bin/aarch64-linux-gnu-"
        export CLANG_TRIPLE=aarch64-linux-gnu-

        export KBUILD_BUILD_USER="rsuntk"
        export KBUILD_BUILD_HOST="rsuntkOrgs"
        export BUILD_START=`date`
        export SELINUX_STATE="Enforcing"
        export IS_CI=true
        export DEFAULT_KSU_BRANCH="optional_kp"
        export LTO="${{ github.event.inputs.LTO }}"
        export LLVM=1
        export LLVM_IAS=1

        # clone mtk connectivity
        #rm -rf drivers/misc/mediatek/connectivity && cd drivers/misc/mediatek/ && git clone https://github.com/rsuntkOrgs/mtk_connectivity_module --depth=1 -b staging-4.19 connectivity && rm -rf connectivity/.git && cd ../../..

        export DEFCONFIG="${{ steps.getdev.outputs.DEFCONFIG }}"
        export DEVICE="${{ steps.getdev.outputs.DEVICE_MODEL }}"
        export DEVICE_ID="${{ steps.getdev.outputs.DEVICE_ID }}"
        export TARGET_PRODUCT="${{ steps.getdev.outputs.DEVICE_MODEL }}"
        
        export KERNELSU="${{ github.event.inputs.KSU }}"
        
        bash $(pwd)/build.sh kernel --jobs $(nproc --all) `echo $DEFCONFIG`
        
        if [[ "${{ github.event.inputs.KSU }}" = "true" ]]; then
        	KSU_REV_COUNT=$(cd KernelSU && git rev-list --count HEAD)
        	KSU_VERSION=$(expr 10200 + $KSU_REV_COUNT)
        else
        	KSU_VERSION="No KernelSU"
        fi
        echo "- KernelSU version: $KSU_VERSION"
        
        ## CREATE buildDetails.txt
        printf "Localversion: `./getutsrel`
        Clang version: `clang -v 2>&1 | grep ' version ' | sed 's/[[:space:]]*$//'`
        Build date: `echo $BUILD_START`
        Defconfig: `echo $DEFCONFIG`
        KernelSU: `echo $KSU_VERSION`
        LTO: `echo $LTO`
        SELinux: `echo $SELINUX_STATE`
        " >> buildDetails.txt
        
        echo "TITLE=Galaxy `echo $DEVICE_ID` Kernel" >> $GITHUB_ENV
        
        echo ""
        echo "===================================================="
        strings out/arch/arm64/boot/Image | grep "Linux version"
        echo "===================================================="

        mv out/.config out/build_config.txt
        gitsha1=$(git rev-parse --short HEAD)
        buildDetails="`make kernelversion`-`echo $DEVICE`_`echo $gitsha1`-`date +'%Y%m%d%H%M%S'`" && echo "buildDetails=$buildDetails" >> $GITHUB_OUTPUT
      working-directory: kernel_root
      
    - name: Upload config
      uses: actions/upload-artifact@v4
      with:
        name: Config-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/out/build_config.txt
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-${{ steps.buildKernel.outputs.buildDetails }}
        path: |
          kernel_root/out/arch/arm64/boot/*.gz
          kernel_root/out/arch/arm64/boot/dts/mediatek/*.dtb

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/AnyKernel3/*
        compression-level: 9
        
    - name: Upload to Telegram
      if: github.event.inputs.UPLOAD_TO_TG == 'true'
      env:
        CHAT_ID: ${{ steps.getdev.outputs.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        if [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          ZIP=$(find `pwd` -name "*.zip")
          git clone https://github.com/rsuntk/rsuntkBotScript.git --depth=1 i && cp ./i/* . && rm -rf i
          bash $(pwd)/rsuntkbot.sh $ZIP "`cat buildDetails.txt`"
        fi
      working-directory: kernel_root
        
    - name: Strip LKMs
      if: github.event.inputs.UPLOAD_LKM == 'true'
      run: |
        # Cleanup zip
        rm -rf *.zip

        # Create folder
        mkdir ../kernel_object_tmp
        mkdir kernel_object

        # Only move neccessary path!
        find $(pwd) -type f -name "*.ko" -exec mv {} ../kernel_object_tmp \;
        LIST=$(find ../kernel_object_tmp -type f -name "*.ko")

        # Start stripping
        for file in $LIST; do
          echo -e "- Stripping `basename $file`"
          $(pwd)/toolchains/clang/bin/llvm-strip "$file" --strip-unneeded
        done
        mv ../kernel_object_tmp/*.ko $(pwd)/kernel_object/
      working-directory: kernel_root
        
    - name: Upload LKM
      uses: actions/upload-artifact@v4
      with:
        name: LKM-${{ steps.buildKernel.outputs.buildDetails }}
        path: kernel_root/kernel_object/*
